### ISSUE TITLE
Get warnings for `No main.scss` even though my module is js only

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#138]
```
mandrews@MATT ~/sandboxes/next-feature-flags-client (iso-events) $ origami-build-tools verify
No main.scss
```

Have I missed something?  Is there a way to stop it warning me?

[Sorry for all the issues — I'm really enjoying working with the new super clean OBT!]

**Comment by AlbertoElias** [comment]
I believe the warning was removed entirely. Can this be closed?

**Comment by matthew-andrews** [comment]
:+1:
