### ISSUE TITLE
"init" or "scaffold" task

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#139]
How about a task that sets up:
- directory structure
- default file names
- origami.json
- bower.json
- .gitignore
- README
- …

With an interactive CLI, a bit like Yeoman does?

The main use case: as a developer I'd like to spend time building the component, not setting it up.

**Comment by triblondon** [comment]
Agreed to create `obt init product` and `obt init component`, based on Callum's work.

**Comment by onishiweb** [comment]
Is this still an issue, in https://github.com/Financial-Times/ft-origami/issues/326 we settled on a separate repo as a boilerplate, is it worth looking at making a script to clone the repo or can this be closed?

**Comment by AlbertoElias** [comment]
I think that was the idea of what this init task would do

**Comment by onishiweb** [comment]
ok cool, we can look into that soon then hopefully.

**Comment by AlbertoElias** [comment]
we currently have the [o-component-boilerplate](https://github.com/Financial-Times/o-component-boilerplate) repo, might be good to just promote that?

**Comment by JakeChampion** [comment]
Could an MVP for this be a new OBT task which `curl`s the [zip endpoint for o-component-boilerplate](https://github.com/Financial-Times/o-component-boilerplate/archive/master.zip)?

**Comment by onishiweb** [comment]
@JakeChampion yep, think that could be a great addition 👍

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
