### ISSUE TITLE
Origami Build Tools needs tests!

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#144]
This little pull request managed to break all of Next FT's builds :smile: https://github.com/Financial-Times/origami-build-tools/pull/143.

I think everyone was out at lunch so I just pushed a fix to master here (please review):
https://github.com/Financial-Times/origami-build-tools/commit/2b04579bcae8af4e9c2a2dcb1c1b32e2ab4501e5

I think it's a good idea if we wrote some tests for OBT.

For starters this should be achieved by having a few “sample” apps that it can build and asserting that the builds finish without exiting with a non-zero exit code.

Also it should pass usual linting and lintspace rules (with appropriate modifications as this is a JavaScript node CLI not a browser thing).

For my little Heroku deployment tool I wrote tests that _actually_ create real apps on Heroku, actually deploys to actual Heroku and made actual `GET` request to check that the build had “done the right thing”—a similar approach (starting small and simple) could be quite effective for OBT—https://github.com/matthew-andrews/haikro/blob/master/test/even-simpler-deployment.test.js.

// cc @adgad @commuterjoy @kaelig @triblondon @AlbertoElias

**Comment by triblondon** [comment]
Can we close this now?

**Comment by AlbertoElias** [comment]
Yes, I think we can as npm test can't really test if the site looks ok with both versions of Sass, only if it builds ok which I think is not enough
