### ISSUE TITLE
Ability to use build service bundles in a product build

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#149]
If one does (in slightly pseudo code)

```
// fetch a buildservice bundle
curl http://buildservice/js?o-module1,o-module2&umd=true > client/o-modules

// then product code can do
require('./o-modules').module1.method();
```

This would:
 - reduce build and bower install issues & times (but not so much if the modules' sass is needed)
 - make it possible for products to use build service without the need for an additional script tag and use of global variables
 - be compatible with other module loading systems (I think)

So I suggest something like a config option `useBuildService` which:
 - If true, reads the bower.json and gets the equivalent js bundle from buildService
 - if a list of modules gets the equivalent js bundle from buildService

Maybe with additional options `buildServiceOutputFile`, `buildServiceAlias` (to e.g. be able to do `require('o')`

browserify --alias 'client/o-modules' to 'o' main.js -o public/main.js

**Comment by AlbertoElias** [comment]
Why would this help? What's the use case?

**Comment by wheresrhys** [comment]
It was an idea to speed up builds.
