### ISSUE TITLE
Use webpack instead of browserify

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/origami-build-tools#150]
It's faster, and produces smaller bundles.

**Comment by callumlocke** [comment]
Is this still on the cards?

**Comment by AlbertoElias** [comment]
It didn't work nicely with Bower. Maybe looking at jspm would be good

**Comment by imranolas** [comment]
We've replaced the home page build with webpack. Bower seems to play just fine.

https://github.com/Financial-Times/next-front-page/blob/master/webpack.config.js

**Comment by AlbertoElias** [comment]
Done!
