### ISSUE TITLE
'release' task?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#153]
We could automate all of these steps under a 'release' task:
1. run `obt build, demo, test, verify`
2. bump version up in `bower.json` (would mean we'd need to use bower version number)
3. stage and commit the `bower.json` file
4. tag with new release
5. push to origin with tag
6. create a release in github

``` shell
$ obt release patch # log: cheers
$ obt release minor # prompt: Have you deprecated stuff properly?
                          # > point to url of docs explaining why
$ obt release major # prompt: are you sure? That's a pretty big deal, blah blah
```

Thoughts?

**Comment by onishiweb** [comment]
Is this still worth looking into?

**Comment by AlbertoElias** [comment]
this could be quite nice I think

**Comment by JakeChampion** [comment]
I'm not sure this feature is worth the effort as the workflow for releasing a new origami component is to create a github release via the github website.
