### ISSUE TITLE
Consider temporarily removing sassdoc

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#155]
sassdoc expects npm v2, which is not the default install (1.4.x is). This doesn't mean OBT *always* fails to install but it does seem to add to the flakiness. A number of bugs are reported over at sassdoc with 'install npm v2' as the solution e.g. https://github.com/SassDoc/sassdoc/issues/288#issuecomment-65846634

As sassdoc is only a requirement for origami authors/the registry would it be prudent to remove it from obt for now. Systems that need the docs can install and run sassdoc directly.

@geek-caroline Does this sound relevant to the problems you experienced earlier today?

**Comment by AlbertoElias** [comment]
@wheresrhys We updated to sassdoc v2, is this still happening?

**Comment by wheresrhys** [comment]
Haven't had any issues for a while, but that's probably because I already upgraded to npm 2. You'd need to rollback npm and try obt install to see if it still happens

**Comment by AlbertoElias** [comment]
Tbh, if everyone is using npm v2 and not having this issue. I think sassdoc should stay. @geek-caroline are you having any issues?

**Comment by geek-caroline** [comment]
@AlbertoElias nope, no issues, however, I haven't done anything since I managed to get things running  (but couldn't tell you how I managed that).  I guess leave things as they are as you suggest but keep an eye out for the next new dev to try and set up their environment from scratch see if they have any issues and reopen if needed?

**Comment by AlbertoElias** [comment]
Will do.

**Comment by wheresrhys** [comment]
But npm 2 isn't the default so potentially a lot of new users will hit this problem and the solution isn't obvious.

I'd favour a variant of @kaelig's [suggestion](https://github.com/Financial-Times/origami-build-tools/issues/155#issuecomment-66655421): How about if when any install step fails a message is output linking to a troubleshooting guide, which would be a markdown page within the obt repo?

**Comment by AlbertoElias** [comment]
I think making npm v2 the default is better for newcomers

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by samgiles** [comment]
Given we have the SassDoc service, does it make sense to have it in the
build tools?

On 9 March 2015 at 12:38, Alberto Elias <notifications@github.com> wrote:

> I think making npm v2 the default is better for newcomers
>
> --
>
> ------------------------------
> This email was sent by a company owned by Pearson plc, registered office
> at
> 80 Strand, London WC2R 0RL. Registered in England and Wales with company
> number 53723.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/issues/155#issuecomment-77845663>
> .
>



-- 
*Sam Giles*
Developer
FT Labs

For Origami questions: origami.support@ft.com

Number One Southwark Bridge, London SE1 9HL

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
Even if it's to check that the docs are created properly, I think so. If
not, it's quite easy to remove entirely

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by wheresrhys** [comment]
> npm 2 isn't the default 

... meaning that a fresh install of node installs npm@1.x. We can't change this

**Comment by AlbertoElias** [comment]
I think Node 0.12 does install npm 2.x and we're going to update to 0.12 shortly

**Comment by wheresrhys** [comment]
> we're going to update to 0.12 shortly

But again, you can't make all users up grade to v0.12 - there may be good reasons why they can't (e.g. @matthew-andrews rolled back to 0.10 the other day because of memory leaks in 0.12). Just assuming that every user is OK to upgrade node, particularly when they have no obvious way of identifying their npm version is the cause of the failed sassdoc install, isn't very user friendly.

**Comment by AlbertoElias** [comment]
Well, as this is currently not affecting anyone, let's see if it comes up
again and we'll see what the best way to go around it is.

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
