### ISSUE TITLE
JSHint warnings don't fail build on OBT

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#158]
https://travis-ci.org/Financial-Times/origami-build-tools/builds/43842714

**Comment by wheresrhys** [comment]
ft-api-client is failing like nobody's business, so I guess it's merged

**Comment by AlbertoElias** [comment]
@wheresrhys Not yet actually #184

**Comment by wheresrhys** [comment]
ah, I think it must be lintspaces then

**Comment by matthew-andrews** [comment]
i think this is fixed now?

**Comment by robin-marr-ft** [comment]
Yep, the fail reporter has been added so it should kill builds now.

On 29 January 2015 at 14:07, Matt Andrews <notifications@github.com> wrote:

> i think this is fixed now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/issues/158#issuecomment-72029901>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
Yup :) Lintspaces doesn't fail build though, the module doesn't implement it
