### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by robin-marr-ft** [Financial-Times/origami-build-tools#172]
Currently npm install origami-build-tools fails on windows with the below errors:
npm ERR! Failed resolving git HEAD (https://github.com/Financial-Times/debowerif
y.git) fatal: ambiguous argument 'master': unknown revision or path not in the w
orking tree.
npm ERR! Failed resolving git HEAD (https://github.com/Financial-Times/debowerif
y.git) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (https://github.com/Financial-Times/debowerif
y.git) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (https://github.com/Financial-Times/debowerif
y.git)
npm ERR! Error: Command failed: fatal: ambiguous argument 'master': unknown revi
sion or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\robin.marr\workspace\origami-build-tools
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\robin.marr\workspace\origami-build-tools\npm-debug.log
npm ERR! not ok code 0

Not sure if this is the same issue as #119

**Comment by kaelig** [comment]
Thank you! Let me bump up the version and let me know if that now works.

**Comment by robin-marr-ft** [comment]
Yep 2.6.2 installs fine now, thanks for the quick turn around

**Comment by kaelig** [comment]
Fantastique, thanks!
