### ISSUE TITLE
Ignore comments during space linting

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#186]
In SassDoc, comments can contain some amount of Markdown, for example, for line breaks and inline code blocks:

``` scss
/// Surface the layout currently displayed to make it readable in JS.  (there are two spaces here)
/// In IE 8, assume it is `$o-grid-fixed-layout`
```

![screenshot 2015-01-09 12 07 51](https://cloud.githubusercontent.com/assets/85783/5679478/25e2ca5c-97f8-11e4-8e44-d3a1e73e170e.png)

Unfortunately the linter will raise errors because of the two spaces at the end of the first line.

To avoid that, can we setup the linter to avoid linting comments?

**Comment by kaelig** [comment]
Looks like that can be done using a configuration tweak: https://www.npmjs.com/package/gulp-lintspaces

**Comment by kaelig** [comment]
We should probably fasttrack this so that the SassDoc service can have better documentation syntax support. @AlbertoElias do you want to have a look?

**Comment by onishiweb** [comment]
Is this still in need of looking into?

**Comment by AlbertoElias** [comment]
yup
