### ISSUE TITLE
Test if including the module twice outputs helper classes only once

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#187]
To ensure we have some sort of "include once" set up in non-silent mode.

The test should verify that including the module twice outputs the same as when it's included once in non-silent mode.

Thoughts?

**Comment by AlbertoElias** [comment]
To test this, when the module is included twice, should the css output size be exactly the same as when it's only included once?

**Comment by kaelig** [comment]
@AlbertoElias seems like a good way to do it.

This would be very useful for Next.

/cc @matthew-andrews

**Comment by matthew-andrews** [comment]
i like it :+1:

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
