### ISSUE TITLE
Run tasks over just styles or js

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#188]
In local development if I know my sass passes linting already but js doesn't it'd speed things up if I could run obt verify over just js. I'd like to be able to call `obt verify --js-only` or `obt verify --sass-only`.

Similarly, it'd be faster if watch forwarded information about file types to the tasks it runs.

**Comment by AlbertoElias** [comment]
You can run only one of the subtasks via a gulp task in a gulp file, and the command line just runs general tasks. I don't think at the moment we should get into allowing configuration to run just some subtasks, and products should be using gulpfiles

**Comment by AlbertoElias** [comment]
I'm going to close this for now. If it keeps coming up, we'll reopen the issue.
