### ISSUE TITLE
What happened to being able to extend the default jshint config?

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#189]
I thought the original decision was that products could override individual properties of jshintr but the defaults would be the origami set of rules (particularly useful for globals). And also that modules would be prohibited from doing this. Looking at the code it appears the only thing implemented is the ability to use a product/module's own json config in full.

**Comment by AlbertoElias** [comment]
How would you do it otherwise?

**Comment by wheresrhys** [comment]
just a normal default config implementation: for each possible jshint config property use the user defined one if it exists, otherwise use the obt default, otherwise leave undefined

**Comment by matthew-andrews** [comment]
it doesn't seem worth the complexity of writing and maintenance overhead of looking after code that crowbars inheritance into JSON…  jshint files are tiny, if you need to deviate you can achieve this with per file overrides or just provide your own…

**Comment by AlbertoElias** [comment]
Yeah, I think we should leave it as is for now at least. I'll close and if we see that this comes up often and there's enough benefit, we'll look into it
