### ISSUE TITLE
Please document demos' `config.json`

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#196]
And generally how to set a repo up for demos and how it works, etc :-)

**Comment by matthew-andrews** [comment]
which files are generated, which one are not

**Comment by AlbertoElias** [comment]
The demo section links to this: http://origami.ft.com/docs/component-spec/modules/#demo-config-file Is that enough? Is it hard to find?

**Comment by matthew-andrews** [comment]
Ah perfect… sorry! // cc @leanne1
