### ISSUE TITLE
Install accepts incompatible sass 3.4

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#201]
If sass 3.4 is already installed then the install task passes

```
$ obt install
no package.json, skipping npm install...
JSHint 2.5.11 already installed
sass gem 3.4.10 already installed.
Bower 1.3.12 already installed
scss-lint gem 0.33.0 already installed.
bower install...
```

This (as well as the annoyance of obt insisting on upgrading from e.g. scss-lint@0.27.5 to scss-lint@0.27.6, making the install slower) could be fixed by using node-semver for those dependencies which use semver properly.

**Comment by wheresrhys** [comment]
https://github.com/Financial-Times/origami-build-tools/pull/209

**Comment by AlbertoElias** [comment]
Can this be closed?

**Comment by AlbertoElias** [comment]
Nudging @wheresrhys

**Comment by wheresrhys** [comment]
Probably fixed by that semver PR so yes

On Thursday, April 30, 2015, Alberto Elias <notifications@github.com> wrote:

> Nudging @wheresrhys <https://github.com/wheresrhys>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/issues/201#issuecomment-97806128>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
