### ISSUE TITLE
Clearer debug info when failing to install gems

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#202]
After a failed gem install the preferred action for the user would be to change the permissions on their gem directory and try again. Second choice would be to e.g. `sudo gem install sass@3.3.14` (`update` is best avoided). Both these would be useful to put in the error messages

**Comment by kaelig** [comment]
We probably don't want to `sudo` any commands but we could display to the user a message asking if they could try it themselves?

**Comment by wheresrhys** [comment]
I ended up having to do sudo as, after chowning ~/.gem and Libraries/[rest of path to installed gems] I then had problems installing in `/usr/bin` which I don't want to chown. I probably should get gem to install somewhere else and add to my path (or in a subdirectory of `usr/bin`) , but AFAIK I'm just using the default settings.

But yes you're right, sudo shouldn't be advised really
