### ISSUE TITLE
npmTest not erroring properly

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/origami-build-tools#206]
@matthew-andrews says:

>I actually broke this in this PR:- https://github.com/Financial-Times/origami-build-tools/pull/193/files#diff-6a5945ca98ba77b07f1c75a9d4888aebR135

>Which shows even though Travis has been telling us things are good, the tests haven't actually been passing for a few days…

>I don't think the npmTest task works properly :-) @AlbertoElias

**Comment by AlbertoElias** [comment]
Should be erroring properly now.

**Comment by matthew-andrews** [comment]
thank you o-team!
