### ISSUE TITLE
include release notes in upgrade obt message

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#207]
so that it reads e.g

```sh
Origami Build Tools update available: 2.8.0 (current: 2.7.0)
Use origami.json browserFeatures property to use the polyfill service.
Asset hashing with tests
```

**Comment by AlbertoElias** [comment]
I'm not sure I agree with this. It's not super simple and the message can become quite messy

**Comment by triblondon** [comment]
Agree with Alberto.  Not that hard to go to the repo to find out what the update brings, and you may be several versions behind.

**Comment by wheresrhys** [comment]
I agree the cost of achieving is probably higher than the benefit. Any objections if I submit a PR with a link to the release notes on github; that seems to be a good compromise, making it really easy-peasy to go to the repo to find out.

**Comment by AlbertoElias** [comment]
@wheresrhys that seems good to me
