### ISSUE TITLE
Upgrade to Node 0.12

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/origami-build-tools#211]

**Comment by matthew-andrews** [comment]
We've started doing this too :)

**Comment by samgiles** [comment]
I've seen some issues with local dev and Node 0.12 for the Build Service (which has been on 0.11 for a long time).  I need to spend some time one evening and pinpoint it, but just be aware, _sometimes_ it doesn't seem to accept incoming TCP connections and I have to restart the process a few times.  I can't see anyone else reporting this issue so it _might_ only be in combination with `--harmony`.

**Comment by samgiles** [comment]
(Shouldn't be an issue generally though for anything but the demo local server in obt?)

**Comment by AlbertoElias** [comment]
This has been done already!
