### ISSUE TITLE
Warnings are being promoted to errors

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#213]
We're getting closer :smile: 

![screen shot 2015-02-10 at 15 33 37](https://cloud.githubusercontent.com/assets/825088/6130001/3cacebd6-b13a-11e4-8fc9-f0b0639c173c.png)

Possibly:-
- Warnings (e.g. above) shouldn't break builds

Nicer solution?
- Maybe a `--strict` mode where all warnings become errors

**Comment by kaelig** [comment]
You're right, only errors should break the build!

**Comment by AlbertoElias** [comment]
But is your problem an error or a warning?

**Comment by matthew-andrews** [comment]
I think the `[W]` means warning?

**Comment by matthew-andrews** [comment]
![screen shot 2015-02-10 at 15 43 14](https://cloud.githubusercontent.com/assets/825088/6130204/8f4b01b0-b13b-11e4-8aa3-c4e18744ec4f.png)

Here's another…  seems to suggest `[E]` => error, `[W]` warning?

**Comment by kaelig** [comment]
That's correct. The build should break on errors but not warnings.

**Comment by AlbertoElias** [comment]
It should indeed, but we're just using the gulp plugin's fail reporter.
Might need to look into extending that or making a pr on the plugin.

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.
