### ISSUE TITLE
Switch from CSSO to clean-css

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#223]
CSSO has a few annoying bugs and doesn't have much traction from the community anymore.

I suggest that we test [clean-css](https://github.com/jakubpawlowicz/clean-css) as a replacement, which seems much better at first glance. 

I also like that [gulp-minify-css](https://github.com/jonathanepollack/gulp-minify-css) has full sourcemap support.

**Comment by AlbertoElias** [comment]
Is the output better?

**Comment by kaelig** [comment]
What do we mean by "better output"? Is it "much smaller" or "that works"?

**Comment by AlbertoElias** [comment]
@kaelig if we can get both, great :D

**Comment by kaelig** [comment]
I've tested both in the forms module and:
- csso: bugs
- clean-css: no bugs, smaller by a few 0.x KB

Go ahead :)
