### ISSUE TITLE
Script that tars obt with node_modules

### ISSUE THREAD

**Issue by AlbertoElias** [Financial-Times/origami-build-tools#236]
To improve install time on CI (currently over a minute), we want to try building a script that:
1. Runs npm install
2. Runs npm dedupe
3. Tars everything
4. Pushes it to an S3 bucket or an alternative from where it can be fetched from CI

**Comment by callumlocke** [comment]
Beware of possible problems with compiling native extensions on a different system than what it's going to be used on. For example node-sass is very particular about which architecture and even V8 version is is compiled for; if you switch from Node 0.11 to 0.12 you have to `npm rebuild` it.

**Comment by onishiweb** [comment]
Any update on this? Or has the switch to CircleCI made this a bit redundant?

**Comment by AlbertoElias** [comment]
There might be better alternatives, but npm install on obt is waaay too slow

**Comment by JakeChampion** [comment]
I don't think this is for OBT to solve.

For installations on CI, CircleCI already cache `node_modules` directories.

For installations on developer machines, NPM version 3 & above also have caching features built-in and can be enabled by a user via their `~/.npmrc` file. They would need to add `cache-min=9999999` to this file.
