### ISSUE TITLE
Don't require JSHint to be installed globally.

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#243]
https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/install.js#L217-239

It's not actually necessary.

```
$ npm uninstall -g jshint
$ npm install jshint # look no -g
$ which jshint
node_modules/.bin/jshint
```

(Provided your `$NODE_PATH` has `:node_modules/.bin` on it)

**Comment by matthew-andrews** [comment]
And OBT can just `require` it directly……  in fact it does, via gulp-jshint!

**Comment by AlbertoElias** [comment]
But if we don't install it globally, you'll end up with a node_modules folder in a module that might not even have a package.json, right?

**Comment by matthew-andrews** [comment]
> But if we don't install it globally, you'll end up with a node_modules folder in a module that might not even have a package.json, right?

I'm suggesting that Origami Build Tools not install JSHint at all.  If you want to JSHint your component you shouldn't use `jshint` directly anyway, you should use `origami-build-tools verify` because just calling `jshint` will have the wrong config…

> not everyone has their path set up like that

They should do but that's not really the point…  I think all of this stuff:-

https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/install.js#L217-239

Can be simply deleted

**Comment by AlbertoElias** [comment]
Is it the same for scss-lint?

**Comment by matthew-andrews** [comment]
potentially…… but that's a ruby gem isn't it?  does the gulp task require it to be installed?

**Comment by AlbertoElias** [comment]
@matthew-andrews ah, that's right! Oh well, we can at least potentially remove jshint, I'll take a look.
