### ISSUE TITLE
Origami Build Tools wont install with the latest version of npm

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/origami-build-tools#245]
[But it looks like a problem with gulp-lintspaces]

```
npm WARN package.json fetchres@1.1.0 No repository field.
npm WARN package.json ft-next-express@7.9.2 No repository field.
npm WARN package.json next-ft-api-client@2.1.0 No repository field.
npm WARN prefer global nodemon@1.3.7 should be installed with -g
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! path /Users/harry.spriggs/next/next-grumman/node_modules/origami-build-tools/node_modules/gulp-lintspaces/node_modules/lintspaces/node_modules/editorconfig/bin\editorconfig
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, chmod '/Users/harry.spriggs/next/next-grumman/node_modules/origami-build-tools/node_modules/gulp-lintspaces/node_modules/lintspaces/node_modules/editorconfig/bin\editorconfig'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/harry.spriggs/next/next-grumman/npm-debug.log
```

Doing `npm install -g npm@2.1.18` (a known working version of npm fixes the issue).  Probably not necessary to fix in OBT as such but if you had a chance to take a look maybe we could fix it in the dodgy dependency ……

[@matthew-andrews actually writing this under Harry's account]

**Comment by quarterto** [comment]
This is fixed in between `editorconfig@0.11.4` (which `lintspaces` uses) and `0.12.2` (the latest on npm). There's nothing [between the two versions](https://github.com/editorconfig/editorconfig-core-js/compare/50e0dba81b2f7f3e9ea4f701f2c65dd3f482cd4c...master) that looks like it fixes it though, which is odd.

**Comment by AlbertoElias** [comment]
Thanks @quarterto !!

**Comment by quarterto** [comment]
Current status: this is a bug in npm. A workaround would be to downgrade it to 2.7.5 or below. See the above linked issue. Closing the issue here because there's nothing we can do about it.

**Comment by matthew-andrews** [comment]
This is now going to cause mad problems for Next (and others) because the affected version of npm has now hit Travis.

https://travis-ci.org/Financial-Times/next-grumman/builds/62516286

**Comment by AlbertoElias** [comment]
I'll limit to 2.7.5. Has the error been reported to npm?

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by quarterto** [comment]
npm/npm#7992

**Comment by callumlocke** [comment]
Can we just remove gulp-lintspaces? It looks unmaintained to me. And don't the language-specific linters already cover whitespace issues?
