### ISSUE TITLE
Nightwatch Screenshots

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/origami-build-tools#250]
It would be good if we could find a way to get Travis to make the nightwatch failure screenshots available somewhere.  The console output is decent enough, but figuring out why some tests failed would go a lot faster if we could see the images.

**Comment by AlbertoElias** [comment]
@samgiles What do you think? Maybe extending the proxy to have some kind of endpoint to save them in an S3 bucket? Would it be time consuming to implement?

**Comment by samgiles** [comment]
Or just push directly into S3? I don't want to extend the proxy beyond just that, a proxy, because then you have to start writing code and maintaining it etc.
