### ISSUE TITLE
Often fails to install sass on Travis

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#252]
Would be really helpful if someone had chance to look into this.

![screen shot 2015-04-27 at 16 29 20](https://cloud.githubusercontent.com/assets/825088/7351023/a14f7396-ecfa-11e4-9133-b91835db60d2.png)

**Comment by matthew-andrews** [comment]
We've also seen this on Codeship too :disappointed:

**Comment by samgiles** [comment]
@AlbertoElias didn't we see this on the OBT build? And it seemed to work
when we turned off 'sudo: false'.

On 27 April 2015 at 16:30, Matt Andrews <notifications@github.com> wrote:

> We've also seen this on Codeship too [image: :disappointed:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/issues/252#issuecomment-96709481>
> .
>



-- 
*Sam Giles*
Developer
FT Labs

For Origami questions: origami.support@ft.com

Number One Southwark Bridge, London SE1 9HL

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
Yeah, removing sudo: false seemed to work. We haven't released it though

**Comment by matthew-andrews** [comment]
the screenshot I added was for a build that had sudo: false

**Comment by AlbertoElias** [comment]
That's what I mean, that needs to be removed, and it is removed in master

**Comment by matthew-andrews** [comment]
but we need `sudo: false` and it works most of the time… just occasionally fails.

**Comment by matthew-andrews** [comment]
(i'm talking about Next apps, not origami-build-tools Travis job itself)

**Comment by matthew-andrews** [comment]
also codeship doesn't have the concept of `sudo: false` that we can't remove it & solve that problem here

**Comment by samgiles** [comment]
I'll see if I can figure this out when I get a chance then.

On 28 April 2015 at 09:13, Matt Andrews <notifications@github.com> wrote:

> also codeship doesn't have the concept of sudo: false that we can't
> remove it & solve that problem here
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/origami-build-tools/issues/252#issuecomment-96968868>
> .
>



-- 
*Sam Giles*
Developer
FT Labs

For Origami questions: origami.support@ft.com

Number One Southwark Bridge, London SE1 9HL

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by AlbertoElias** [comment]
Hopefully this won't be an issue with the beta

**Comment by AlbertoElias** [comment]
@matthew-andrews Is this still happening?

**Comment by matthew-andrews** [comment]
nope, no more sass gem to have problems with and we don't use travis neither :-)
