### ISSUE TITLE
More intelligent watch

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#259]
Would it be possible to make the watch a little more intelligent?

e.g. changes to javascript only rebuilds javascript, scss changes only trigger css changes

Feels like this would be quite a simple change.

**Comment by matthew-andrews** [comment]
cc @wheresrhys

**Comment by matthew-andrews** [comment]
this is how we achieved this in nbt https://github.com/Financial-Times/next-build-tools/blob/master/tasks/build.js#L31-36

**Comment by AlbertoElias** [comment]
Fixed in #263 

Can we close?

**Comment by matthew-andrews** [comment]
looks good to me!
