### ISSUE TITLE
Replace scss-lint with sass-lint

### ISSUE THREAD

**Issue by aarmour** [Financial-Times/origami-build-tools#268]
[It's not ready yet](https://github.com/sasstools/sass-lint/issues/6#issuecomment-110215844), but with the switch to libsass it would be nice to eventually remove the Ruby dependency.

**Comment by kaelig** [comment]
In the long term it's definitely something we need to do.

Right now it's nowhere near as mature as scss-lint, so feel free to contribute!

**Comment by Snugug** [comment]
Hey awesome people! We've got a few alpha releases out; all that's left for you to do is start contributing rules! We could use all the help we can get to roll this out quickly!

**Comment by kaelig** [comment]
Hey Sam, thanks for coming here to see what we do :)

There is a plan to switch to sass-lint but it maybe not with such an early stage build. We've happily been guinea pigs on scss-lint but now that we're happy with our linting configuration I'm not sure we'll want to go through this again.

**Comment by Snugug** [comment]
Hey Kaelig!

The current build is stable, the alpha designator is simply because of the lack of rules (and some wonkiness with how config works from a `yml` file). The next release will most likely be a full BETA now that I've got the majority of rules written. If you could take a look and LMK [what's missing from you adopting](https://github.com/sasstools/sass-lint/issues/6#user-content-rules) (or at least playing with adopting) it, that'd help me greatly get this out the door. I'm aiming for an early September launch presuming all of my testing/rule writing goes as planned.

**Comment by kaelig** [comment]
Thank you for the update, I had no idea so many rules were already implemented.

I've ran a diff between [the rules we enabled](https://github.com/Financial-Times/origami-build-tools/blob/master/config/scss-lint.yml) and the ones that are in sass-lint:

```diff
-EmptyLineBetweenBlocks
-EmptyRule
+BangFormat
+BorderZero
+DebugStatement
+DeclarationOrder
+DuplicateProperty
+ElsePlacement
 FinalNewline
+HexLength
+HexNotation
+HexValidation
 IdSelector
-Indentation
+ImportPath
+ImportantRule
 LeadingZero
 NameFormat
 NestingDepth
 PlaceholderInExtend
-PropertySortOrder
 PropertySpelling
+QualifyingElement
 SelectorDepth
+SelectorFormat
 Shorthand
 SingleLinePerProperty
 SingleLinePerSelector
 SpaceAfterComma
 SpaceAfterPropertyColon
 SpaceAfterPropertyName
+SpaceBeforeBrace
 SpaceBetweenParens
-SpaceBeforeBrace
 TrailingSemicolon
+TrailingZero
+UnnecessaryMantissa
+VendorPrefix
```

Note that we're using an old version of scss-lint (0.35) so there might be old rules in there.

Hope it helps.

**Comment by Snugug** [comment]
Thanks!

**Comment by onishiweb** [comment]
As mentioned in https://github.com/Financial-Times/ft-origami/issues/448, JS `scss-lint` is now at `v1` so we can start to look at implementing it now.

**Comment by JakeChampion** [comment]
According to @kaelig's comment, we don't use `DeclerationOrder` (which was mentioned as the only blocker in the [other issue](https://github.com/Financial-Times/ft-origami/issues/448)).

**Comment by JakeChampion** [comment]
Oh, we do, I seemed to have spelt it wrong ... `DeclarationOrder` not `DeclerationOrder`

**Comment by onishiweb** [comment]
I'm going to double check that as I don't think we do actually use it. Not from what I've seen in the last version of the scss-lint file.

**Comment by ironsidevsquincy** [comment]
It's definitely being used, unless I'm missing something

https://github.com/Financial-Times/origami-build-tools/blob/master/config/scss-lint.yml#L39-L40

**Comment by onishiweb** [comment]
Nope, you're not. I didn't get chance to double check. I couldn't remember whether it was either not being used or just not a very strict order implemented. Will set to blocked until that rule is added

**Comment by Snugug** [comment]
Good news everyone! That's not an issue any more!

Sass Lint (the JS Sass style checker) is not a direct port of SCSS Lint, and takes a slightly different approach to rules, favoring small single-purpose rules over larger rules with lots of configuration (kinda like ESLint). We have two rules that replace the `DeclarationOrder` rules in SCSS Lint: [`extends-before-declarations`](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/extends-before-declarations.md) and [`extends-before-mixins`](https://github.com/sasstools/sass-lint/blob/develop/docs/rules/extends-before-mixins.md). There currently isn't a rule `declarations-before-nesting`, but if that's important to y'all A) it should be fairly straight forward to make and B) we'd be happy to include it.

**Comment by onishiweb** [comment]
Awesome news, thanks @Snugug! I'll look to updating the scss-lint file and including Sass Lint over SCSS Lint in the near future. 

In regards to the `declarations-before-nesting` it will probably be useful, so if it's straight forward and you're happy to add it, great. But also, if it's straight-forward we can always look at helping out too! Thanks sir.

**Comment by Snugug** [comment]
We're busy on our next release, but if you open a PR it's fairly easy for us to review those. Take a look at the code for those rules (~30 lines of actual code each, ignoring boilerplate), and if we can get it reviewed soon we may be able to get it out in our next release

https://github.com/sasstools/sass-lint/blob/develop/lib/rules/extends-before-declarations.js
https://github.com/sasstools/sass-lint/blob/develop/lib/rules/extends-before-mixins.js

**Comment by onishiweb** [comment]
Opened PR on Sass Lint: https://github.com/sasstools/sass-lint/pull/866

**Comment by onishiweb** [comment]
Released: https://github.com/sasstools/sass-lint/releases/tag/1.10

**Comment by JakeChampion** [comment]
PR for this #401

**Comment by JakeChampion** [comment]
This was done in #401
