### ISSUE TITLE
Improve obt's cli user-experience?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#272]
Now that we have refactored OBT and made it much better in the past few months, we could probably give a go at improving the overall user-experience of the tool.
### Messages

Here is what a typical Travis build would look like:

![screenshot 2015-06-16 17 09 28](https://cloud.githubusercontent.com/assets/85783/8187900/77a2b518-144a-11e5-896d-9025114d62e2.png)
- "exited with 0" could be replaced by something a bit more exciting (we could look at the copy from tools such as Yeoman, git, npm, gulp, karma, …)
- failures could link to the parts of the spec where we mention coding conventions
- Messages such as "doing X, X successful" are on two lines (see below), but they could be one one line. e.g "Installing X… done"

![screenshot 2015-06-16 17 13 49](https://cloud.githubusercontent.com/assets/85783/8188003/12baad1c-144b-11e5-91b8-f9d8895d36f5.png)
### Options
- options don't follow the Unix way (lowercase + dashes). e.g. `--runServer` should be `--run-server` See #273 
- shorthands such as `obt i` for `obt install` would follow conventions set in npm and bower
### Colors
- There are a few colours but they could be better used.
- Warnings / informations that aren't important in the current context shouldn't appear in red, such as "Origami registry is not configured in a .bowerrc file.  This is OK on automated environments such as Travis CI."

---
1. Should we spend time improving these areas?
2. If so, are there any other things that could improve the UX of OBT?

**Comment by AlbertoElias** [comment]
I'm going to number your different comments:

1. That's a travis thing and doesn't appear in the CLI
2. The .bowerrc links to the spec, what things don't?
3. That's simple
4. Breaking change, raise an issue for v4 if you want
5. Specific suggestions?
6. Agreed, will fix as well

**Comment by kaelig** [comment]
Thanks for the feedback.

About colours: using green for success messages would be a great start.

> The .bowerrc links to the spec, what things don't?
Linting errors, maybe?

**Comment by AlbertoElias** [comment]
Is linting errors really worth it? That would mean having to build custom error reporters that detects what kind of error it is and modifies each one to point to the correct bit in the spec and having to keep of map of this. It's not hard to implement, but I'm not that sure it would be worthwhile. I'm not sure people would really follow the links anyway, and nobody else, that I know of, has mentioned anything of needing slightly more context regarding a linting error

**Comment by kaelig** [comment]
Sorry, I meant that if there is a Sass linting error, OBT could show a link to this page at the bottom of all the errors: http://origami.ft.com/docs/syntax/scss/

But obviously on a per-error basis that would be impossible.
