### ISSUE TITLE
Use browsersync instead of livereload?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#279]
A few reasons why Browsersync is better than what we have in place right now (unless it's a matter of configuration on our side?):
- Browsersync supports in-page asset reloads (instead of reloading the whole page each time something changes).
- Browsersync allows synced scrolling across devices

**Comment by aendrew** [comment]
:+1: for this.

Another advantage: BrowserSync with Weinre, which allows remote debugging over Ngrok — helpful for those occasions when you want to remote debug but somebody seems to have taken your USB-C-to-USB-A cable... :rage1:

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.
