### ISSUE TITLE
Minor issue: Lintspaces no longer displays reason why linting failed

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#281]
![screen shot 2015-06-25 at 15 42 14](https://cloud.githubusercontent.com/assets/825088/8357070/d4404062-1b50-11e5-9a90-6fd8f98cc084.png)

Probably an upstream problem

**Comment by matthew-andrews** [comment]
using > origami-build-tools@3.0.2

**Comment by kaelig** [comment]
Looks like this was fixed. Feel free to reopen if you encounter the same issue again.
