### ISSUE TITLE
obt not reporting bower conflict errors

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/origami-build-tools#285]
I don't know what the cause of my current error is, but that's not the point here. 

The problem for OBT is that, because it's failing inside `obt`, it looks like OBT is the cause. Though in reality it probably isn't. 

![image](https://cloud.githubusercontent.com/assets/224547/8459430/18b26c66-2015-11e5-8298-5e025fea7558.png)

**Comment by adambraimbridge** [comment]
@samgiles

**Comment by samgiles** [comment]
Just to confirm are other builds failing because of this too?

**Comment by adambraimbridge** [comment]
Multiple builds, but only for https://travis-ci.org/Financial-Times/next-beacon-dashboard/. 

Locally, if I run `origami-build-tools install --verbose`, it passes; but if I run `rm -rf bower_components && bower install`, I get an error:

![image](https://cloud.githubusercontent.com/assets/224547/8459994/e3e9bd32-2018-11e5-9cc2-61791f5b3268.png)

**Comment by adambraimbridge** [comment]
I resolved the bower conflict and committed the updated bower.json file. Now builds are passing :+1:

**Comment by JakeChampion** [comment]
This has been resolved in origami-build-tools version 7 👍
