### ISSUE TITLE
rem units?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/origami-build-tools#289]
*Should we automate translation in CSS from `px` values to `rem` values?*

### Pros of rem units

Mostly, accessibility:
- text-only zoom increases the size of text (whereas with `px` values, text keeps the size defined in CSS)
- design scales well (up and down) with @media queries in em + user text zoom

### Cons

- More dependencies in the build process
- The cost of accessibility is the increase in size of CSS payloads
- Components would only work on sites that sites that keep the html font-size at 100%

### Node / Gulp tasks

- https://github.com/robwierzbowski/node-pixrem
- https://www.npmjs.com/package/gulp-pixrem

### Configuration

- Assume 16px root size
- Keep a px fallback. e.g. `font-size: 16px;` compiles to `font-size: 16px; font-size: 1rem;`
- clean-css might minify `font-size: 16px; font-size: 1rem;` down to `font-size: 1rem;`. Make sure agressive merging is disabled.

Thoughts would be appreciated.

**Comment by wheresrhys** [comment]
This is fine for font-size, but what about other sizey properties e.g. width. Opening a can of worms?

**Comment by kaelig** [comment]
It's great to have all properties in rems, we did that at the Guardian and it scales really well. Accessibility wins.

**Comment by kaelig** [comment]
Anything new in that regard? Feel free to close if `px` is the only way.

**Comment by onishiweb** [comment]
It was already discussed some time ago: https://github.com/Financial-Times/ft-origami/issues/162

I'm happy with either unit and agree that `rems` have a few advantages over `px` but considering the amount of work it would be to switch everything over and the substantial change to the spec, it doesn't seem feasible to make the change.

Going to close for now.
