### ISSUE TITLE
Support (or at least, don't prevent) multiple bundles

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-build-tools#304]
Regarding webpack, would you mind adding this feature to the requirements for moving to webpack. We will definitely want to use it (it will mean our apps share one, heavily cached 60kb-ish js file, and each page will then typically only need to download a very small bundle of application code)

### Statement of the requirement:

Should support importing/requiring modules (including subdependencies) from a separate js bundle
e.g. if core.js contains

```
require('dep1')
````

and dep1.js contains

```
require('dep2')
````
and main.js contains

```
require('dep1')
require('dep2')
````
then it should be possible to build bundle.core.js and bundle.main.js in such a way that bundle.core.js contains application code for dep1 and dep2, but bundle.main.js requires dep1 and dep2 from bundle.core.js and doesn't contain any application code for dep1 or dep2

**Comment by AlbertoElias** [comment]
I've got no idea how that would work in webpack and we do need to get it out as soon as possible. So the requirements will continue being to do the same things we have right now. That will break things as some teams are passing in Browserify config options that will now break, and we'll look into adding those capabilities if possible. If you know how this works in webpack, let me know and we can look into it after v4 is released

**Comment by wheresrhys** [comment]
OK will investigate

**Comment by onishiweb** [comment]
Any update on this?

**Comment by wheresrhys** [comment]
next are planning to move away from using obt for js (at least temporarily) as we intend to do a bit of playing around with how we do core + app js bundles. It's certainly not straightforward, and probably not  a use case obt should worry about for the time being
