### ISSUE TITLE
Find safer instructions for installing OBT globally

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/origami-build-tools#305]
![image](https://cloud.githubusercontent.com/assets/224547/9766499/23428890-5711-11e5-8a1d-08e8e67791bc.png)

Look, even I know it's bad to tell origami users (who may not be power users) to blindly use sudo. Sure it's okay for OBT, but the implication is it's safe to use sudo to install any old node package. And it really, really isn't. Right?

http://bfy.tw/1hzs

**Comment by AlbertoElias** [comment]
Yeah, we have started recommending users to configure npm to not use sudo, and we have instructions in our Troubleshoot guide. I'll change the comment to point to that, thanks!

**Comment by adambraimbridge** [comment]
:+1:

**Comment by adambraimbridge** [comment]
Feel free to close this issue. :) 

_You need to use sudo in order to get up and running with origami._ That's not really a problem for any developers who respect the power of sudo. But the origami development target audience is much less likely to know what sudo is. So they get into the habit of blindly copy-pasting sudo commands into their CLI, thinking it's safe to do so. _That's_ the real problem.
