### ISSUE TITLE
Ignore with babelify

### ISSUE THREAD

**Issue by loahou04** [Financial-Times/origami-build-tools#307]
Browserify is running the babelify transform on every module.  This isnt an issue unless you have modules that are not compatible with strict mode.  Can you create an option or that would let consumers list files or even whole directories to an ignore list of babelify so that the modules do not all get wrapped up into strict mode.  

below is a link to an issue that was sent about this to babelify and how to ignore specific directories/files

https://github.com/babel/babelify/issues/48

**Comment by AlbertoElias** [comment]
We don't use babelify anymore, so will close. If this is affected by webpack babel loader, we can look into it. Though all modules should be compatible with strict mode
