### ISSUE TITLE
Create an obt preprocessor for Karma

### ISSUE THREAD

**Issue by robin-marr-ft** [Financial-Times/origami-build-tools#309]
It would be nice not to have to duplicate browserify/webpack configuration into karma conf as it can get stale when changes are made to obt and can cause a lot of work when moving between obt versions, an obt preprocessor would remove these issues.

**Comment by JakeChampion** [comment]
This has been resolved in origami-build-tools version 7 👍 OBT now includes a karma configuration which does the same work as obt build.
