### ISSUE TITLE
Let Webpack create sourcemaps

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/origami-build-tools#315]
Currently OBT creates the sourcemap after Webpack has compiled the JS into a single file, which means it doesn't reference the original source files

Can we let Webpack create the sourcemap, therefore retaining the original references

As an aside, it would be great if the sourcemap was an external file, rather than an inline comment

**Comment by wheresrhys** [comment]
Fixed here Financial-Times/origami-build-tools#323
