### ISSUE TITLE
Demo with --watch doesn't error or exit when there's an error

### ISSUE THREAD

**Issue by expe** [Financial-Times/origami-build-tools#318]
When there's a Sass error:

Current it hangs on `compiling`.
Expect it to error and exit.

It works as expected without the --watch param.

**Comment by triblondon** [comment]
+1 :-)

**Comment by expe** [comment]
Looks like when the watcher runs a task, it isn't running the check here:
https://github.com/Financial-Times/origami-build-tools/blob/master/lib/origami-build-tools-cli.js#L87
