### ISSUE TITLE
obt install not installing bower components

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/origami-build-tools#327]
Really struggling to figure this out…  Still trying to reproduce locally.

**Comment by matthew-andrews** [comment]
This is, err, how we've, err, fixed it.  Hmm.

https://github.com/Financial-Times/next-article/commit/2f98107b5c41257b5b0cdd9000db7a98823bebe6
https://github.com/Financial-Times/next-front-page/pull/312/files

**Comment by AlbertoElias** [comment]
It's weird, our CI installations seem to be working fine =/ Did this start happening with a specific release of obt?

**Comment by matthew-andrews** [comment]
it happened to a few of our apps for a while and now is mysteriously working again…… will monitor on our side and reopen if reoccurs…  could never make a reduced test case.
