### ISSUE TITLE
Support npm 3

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-tools#329]
Installing OBT, npm complains that my `npm` version (v3, stable) is not accepted by OBT's "engines" field.

Can we change OBT so it accepts npm `>=2`?

**Comment by AlbertoElias** [comment]
Does it work properly with v3?

**Comment by callumlocke** [comment]
seems to work fine to me.

It installed fine with npm 3. I haven't tested every OBT feature thoroughly, but I can't see why it would have any problems, unless anything within OBT does something weird like manually reaching into `./node_modules/xxx/node_modules/yyy/` to pick a file out of a subdependency (because npm now organises node modules slightly differently - flattening them all into the first node_modules in your project, where possible).

**Comment by callumlocke** [comment]
Oh, I just encountered exactly that problem. Looks like maybe webpack's babel loader (?) assumes a particular directory structure instead of using using require.resolve.

```
Error: ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /Users/callum.locke/code/ft/project-starter-kit/node_modules/origami-build-tools/node_modules/babel-runtime/helpers/interop-require-default
```

**Comment by AlbertoElias** [comment]
That might be my fault?
https://github.com/Financial-Times/origami-build-tools/blob/master/lib/plugins/babelRuntimePathResolver.js#L9

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by callumlocke** [comment]
that looks like it!

this might work:

```diff
 // Makes paths to babel-runtime polyfills absolute as they're
 // in OBT's node_modules directory and not the module's
 'use strict';
 
 const path = require('path');
 const falafel = require('falafel');
 
 const prefix = /babel-runtime/;
-const rootDirectory = path.resolve(__dirname, '../../node_modules');
 
 module.exports = function babelRuntimePathResolver(file) {
   this.cacheable = true;
 
   return String(falafel(file, { locations: true, ecmaVersion: 6 }, function(node) {
     // Find require() calls
     if (node.type === 'CallExpression' && node.callee.type === 'Identifier') {
       if (node.callee.name === 'require' && prefix.test(node.arguments[0].value)) { //  require("babel-runtime/*")
-        const requirePath = rootDirectory + '/' + node.arguments[0].value;
+        const requirePath = require.resolve(node.arguments[0].value);
         node.update('require(' + JSON.stringify(requirePath) + ')');
       } else {// none of the above, skip
         return;
       }
     }
   }));
 }
```

untested

**Comment by AlbertoElias** [comment]
Fixed!
