### ISSUE TITLE
FastClick's export API broken after switch to Webpack

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-tools#331]
I used to do this (as per fastclick's [usage instructions](https://github.com/ftlabs/fastclick#usage) for CommonJS-style importing):

``` js
import attachFastClick from 'fastclick';

document.addEventListener('DOMContentLoaded', () => {
  attachFastClick(document.body);
});
```

..but now that throws an error. After some debugging, I found this works:

``` js
import FastClick from 'fastclick';

document.addEventListener('DOMContentLoaded', () => {
  FastClick.attach(document.body);
});
```

...that is, the `module.exports` of the fastclick library seems to have been dynamically rewritten to what you _would have_ got if you did `<script src="fastclick"></script>` and simply looked up `window.FastClick`. This is not correct because fastclick specifically [exports its `attach` method](https://github.com/ftlabs/fastclick/blob/9977a916739360ad4ffd7aa19b0016bf375e934b/lib/fastclick.js#L836) as its default export for CommonJS consumers, and its docs state this is intentional. (Personally I've always found it weird and arbitrary that fastclick turns its API upside down just for CommonJS, but that's beside the point.)

I'm guessing this is due to a problem with how Webpack is configured in OBT. Maybe there is something that is helpfully converting global-creating modules into require-able modules, but it's failing to notice that fastclick already uses UMD to define a particular module.exports structure that should be respected.

**Comment by AlbertoElias** [comment]
That is weird, and I'm not sure right now. I did have to add [this](https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/build.js#L49) for all the modules that were looking into exporting as AMD before CommonJS like this case

**Comment by antoligy** [comment]
This behaviour might be caused by this https://phabricator.babeljs.io/T2212 where Babel (correctly) broke compatiblity with CommonJS modules.

This might help - https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by onishiweb** [comment]
@callumlocke is this still an issue?

**Comment by JakeChampion** [comment]
Ping @callumlocke

**Comment by JakeChampion** [comment]
This is not a bug as it was an intentional break made by babel in order to adhere correctly to ES6 modules. Once NodeJS TSC and TC39 settle on an interop between the two modules systems, we will begin to use it.
