### ISSUE TITLE
How to use my own ESLint config from a package.json field?

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-tools#334]
If I'm making a product and I've got my own ESLint config in my `package.json` (in an `eslintConfig` field), I don't see any way I can use this with `obt.verify.esLint()`, because the readme says I can either supply a path to an `.eslintrc` file or it will use the default one.

Is there a way?

**Comment by AlbertoElias** [comment]
I think there have been conversations about this. Does it not work by default? Maybe ask in Slack to see if whoever asked it last time remembers what happened, though I think it was Red Badger =/

**Comment by callumlocke** [comment]
No it doesn't work, nor does an `.eslintrc` file. Although with the latter you can just do `obt.verify.esLint(gulp, path.resolve('.eslintrc'))` to manually feed it in.

**Comment by AlbertoElias** [comment]
Yeah, you can pass it into obt, and that's how I know other teams are doing it but I don't think `gulp-eslint` re-implements the actual searching for a config file like the esLint CLI might do

**Comment by callumlocke** [comment]
I think the issue is that obt always sets an explicit configFile in
gulp-eslint. If you leave this undefined, then eslint will just look for
the closest eslintrc file (or package.json) relative to each linted file,
which is what I want. There should be a way for me to ask for this default
behaviour. Maybe passing false as a second argument to obt.verify.esLint
could mean "don't use the obt eslintrc, just leave it to eslint to find a
config automatically"?

**Comment by AlbertoElias** [comment]
Ok, I'll take a look soon

**Comment by JakeChampion** [comment]
OBT version 7 does not allow for custom eslint configurations, if wanting to use OBT's verify task, the code will need to comply with the origami coding conventions.
