### ISSUE TITLE
Speed up obt verify (add whitelist option)

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#350]
I think `obt verify` takes a while to execute. I think I have a solution for it  as well. Instead of reading all `.js` files and using a blacklist we could have a whitelist of files. Only reading the files which we want to verify might speed the execution of the tasks. 

Line in OBT which reads all `.js` files -- https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/verify.js#L162

**Comment by AlbertoElias** [comment]
I don't think it reads all files. It will only read the ones that aren't blacklisted

**Comment by JakeChampion** [comment]
Ah, yes, that is why the exclude files array needs all strings prepended with a `!`. Would you consider adding the `!` inside of OBT, then the interface for the exclude arrays should be easier for developers to understand.

**Comment by AlbertoElias** [comment]
That would be a breaking change, I would accept a pr for that, but don't have time to add it myself before the next major release.

**Comment by JakeChampion** [comment]
This is done in OBT 7
