### ISSUE TITLE
Use webpack and sass' 'watch' options

### ISSUE THREAD

**Issue by ironsidevsquincy** [Financial-Times/origami-build-tools#352]
Rather than manually watching a load of files ourselves and kicking off a build on change, sass and webpack both have 'watch' options.

https://webpack.github.io/docs/configuration.html#watch
http://sass-lang.com/documentation/file.SASS_REFERENCE.html#using_sass

Using these will greatly improve compilation time

**Comment by onishiweb** [comment]
@AlbertoElias is this still a thing? Should we look into this at some point?

**Comment by AlbertoElias** [comment]
At some point, it would increase dev speed
