### ISSUE TITLE
Publish eslint rules as a shareable configuration

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#367]
### Problem
ESLint linting within a text-editor does not work because the linting files are hidden away inside OBT.

### Proposed Solution
Upload the ESLint rules as a [sharable configuration](http://eslint.org/docs/developer-guide/shareable-configs) which OBT and an Origami modules can depends upon.

If the module name was `eslint-config-origami-components` then origami components could have this inside their respective `.eslintrc` files (or within `package.json`).
``` js
{
    "extends": "eslint-config-origami-components", // You can omit the `eslint-config-` part

    "rules": {
        // Override any settings from the "parent" configuration
        // For example, Next may want to override some rules for their Next components
    }
}
```

**Comment by JakeChampion** [comment]
The same approach can be taken for the ESLint rules used for Origami services.

**Comment by JakeChampion** [comment]
I've made a repo on my personal Github with how this would be implemented. If we agree that should be done I can migrate it to the Financial-Times organisation -- https://github.com/JakeChampion/eslint-config-origami-component

**Comment by rowanmanning** [comment]
This is great, I had no idea that shareable config existed in eslint! Definitely worth doing I think

**Comment by onishiweb** [comment]
The solution to the initial problem looks good to me. 

My only worry would be this gives people a lot easier control over what they could add/ignore. This came up in a discussion recently about editing the eslint settings, which would potentially have been missed had people easier access to overwrite rules like this? But maybe I'm just being overly concerned about it and what will happen will happen regardless...

**Comment by JakeChampion** [comment]
Git repo: https://github.com/Financial-Times/eslint-config-origami-component
NPM page: https://www.npmjs.com/package/eslint-config-origami-component
