### ISSUE TITLE
Demos with the same data but different templates render using the second template

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/origami-build-tools#368]
There is something strange going on where 2 demos using the same data (maybe specifically from a file) are rendering using the same template (template given to the second demo in the origami.json). 

I've done some debugging and so far found that before the `buildHtml` function in `demo.js` returns the data for rendering the demos is all present and correct. It's possible then that the combine function at: https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/demo.js#L133 is what's causing the issue, potentially something to do with the double call of `mustache`?

**Comment by tavvy** [comment]
> maybe specifically from a file

Some further info on this. It seems to be related to importing from a "flat" `.json` data file. 
The problem **does not** occur if using the following method of defining data:

```
data.js
--

module.exports = function () {
	return {
            ...
	};
};
```

**Comment by tavvy** [comment]
PR with a proposed fix for what looks to be the heart of the problem.
Data files passed as a json file were being required but not guarded against mutation, so when re-required by the next template it inherited all the previous properties that had just been set on it.

**Comment by tavvy** [comment]
I made a mock example locally to verify my fix. Is there any real world examples we have to hand that I can test this against?

**Comment by AlbertoElias** [comment]
There was an example, but I can't remember, sorry!
