### ISSUE TITLE
fs error about reevaluating module sources

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/origami-build-tools#376]
```
$ obt install
(node:30173) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
no package.json, skipping npm install...
...
```

This error does not seem to cause a problem, but it is printed every time.

```
$ obt --version
(node:30836) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
v5.1.3
```

**Comment by JakeChampion** [comment]
Is this still occurring @triblondon, I'm struggling to replicate the issue.

**Comment by triblondon** [comment]
I haven't used origami build tools for very long time, so unfortunately I haven't got any recent experience to draw upon, but if no one else is able to reproduce this problem, I would suggest you close it .
