### ISSUE TITLE
no package.json, skipping npm install...

### ISSUE THREAD

**Issue by Dedalos** [Financial-Times/origami-build-tools#382]
Hello,

I am following the steps in your developer guide here (http://origami.ft.com/docs/developer-guide/modules/building-modules/) to set up the environment

Everything it's fine but when I run this command "obt install", I'm having this message:

> no package.json, skipping npm install...
> Installing scss-lint gem
> Install successful.
> Installing Bower...
> Install successful.
> no bower.json, skip bower install...

Also, if I run "gulp" I get this:

> $ gulp
> [19:21:48] No gulpfile found

I already made a git clone from here:

> git clone https://github.com/Financial-Times/origami-manual-build-boilerplate

Maybe I should not use that files??

I'm using the Git Bash, in Windows 7.

Thank you for the light in this issue.

Roy

**Comment by Dedalos** [comment]
By the way that files are in the folder (package.json and bower.json), no idea why is not being used by the script.

**Comment by AlbertoElias** [comment]
We don't officially support Windows, and these issues are very hard to debug and are very specific to each installation.  It might just be that the code that finds those files doesn't work properly on Windows
