### ISSUE TITLE
Add Sentry error tracking for OBT installations

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#387]
Currently OBT does not track errors that may occur on a developer's installation of OBT.

If we add Sentry integration into OBT then all Origami projects will have Sentry error reporting :-)

**Comment by AlbertoElias** [comment]
what do you mean by all origami projects?

**Comment by JakeChampion** [comment]
Build/Image/Polyfill service all report to Sentry
