### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#390]
## Problem

We can not tell how many:
- installations we have
- how many users we have
- how often each command is used
- which versions of Node are they installed/executed under

This information is key in prioritising what work should be done and how it should be done.
## Proposed Solution

Add analytics for each of these stats and possibly more, using the same set-up as our services.
Graphite/Grafana
This solution will of course not work for users when they are offline, I think that is okay as most of our users are online when they are using OBT.
We can decide on whether analytics should be opt-in or opt-out.

**Comment by Limess** [comment]
The metrics added in https://github.com/Financial-Times/origami-build-tools/pull/394 seem to have been removed as part of https://github.com/Financial-Times/origami-build-tools/pull/417.

Was that intentional @JakeChampion? Is this still relevant?
