### ISSUE TITLE
pa11y test doesn't run on CI

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/origami-build-tools#410]
The pa11y test is dependent on there being a pa11y.html file in the `demos/local` directory. This won't currently happen on CI because the local folder is not committed in Git. 

Could we mitigate this by running the demo build task to create the local folder for CI before running the pa11y test?

**Comment by JakeChampion** [comment]
All components are configured to run `obt demo --demo-filter pa11y` before running `obt test` on CI.
