### ISSUE TITLE
OBT doesn't respect directory directive in .bowerrc

### ISSUE THREAD

**Issue by bbcreatv** [Financial-Times/origami-build-tools#411]
When setting the directory in .bowerrc SASS imports fail. Are there any workarounds for this?

```
 "directory": "./static/vendor"
  "registry": {
		"search": [
			"http://registry.origami.ft.com",
			"https://bower.herokuapp.com"
		]
	}

}
```

**Comment by JakeChampion** [comment]
There is no workaround for this issue, we do not support loading bower files from anywhere other than a `bower_components` folder.
