### ISSUE TITLE
CLI hangs for over a minute after completing

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/origami-build-tools#441]
When I run `obt build js`, it generates a built JS bundle and says "Finished running build" after a few seconds, but then it hangs for over a minute before the command exits. Is that normal?

```
time obt build js --js=origami-stuff.js
Webpacking origami-stuff.js

Finished running build

real	1m16.273s
user	0m1.093s
sys	0m0.238s
```

**Comment by JakeChampion** [comment]
This has been resolved in origami-build-tools version 7 👍
