### ISSUE TITLE
Tidy up test output

### ISSUE THREAD

**Issue by alexflorisca** [Financial-Times/origami-build-tools#514]
When runnings the test command, it produces a lot of duplicate output, as per screeenshot below.

![screen shot 2018-03-08 at 15 08 57](https://user-images.githubusercontent.com/3966773/37158295-f367ca5e-22e2-11e8-80aa-7b59b4c40742.png)

**Comment by chee** [comment]
this doesn't seem to happen anymore? it was maybe fixed by one of the recent major versions.

if i've missed something, please reopen
