### ISSUE TITLE
demo data error

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/origami-build-tools#529]
When there is a syntax error in e.g. demo.json, the following error appears:

```
 → Demo data not found: /path/to/demo.json
```

instead of information about the syntax error

**Comment by chee** [comment]
this appears to still be a problem, here: https://github.com/Financial-Times/origami-build-tools/blob/3715752ecdc2a302a8d6803785a004f75c122bdd/lib/tasks/demo-build.js#L76-L86
