### ISSUE TITLE
Feature Request: obt verify to check .npmignore

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#543]
## Problem
We've had components released which have ignored critical file such as the entire demos folder due to having those paths in the `ignore` array within `bower.json`.

## Solution
Check the `ignore` array within the `bower.json` to ensure that it does not contain: `main.scss`, `main.js`, `src` or `demos`.

**Comment by JakeChampion** [comment]
This will stop issues such as https://github.com/Financial-Times/o-lazy-load/pull/2 from happening in the future

**Comment by chee** [comment]
I guess we'll want to change this to checking the `.npmignore`
