### ISSUE TITLE
Upgrade karma.

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#557]

**Comment by SamiTriki** [comment]
There are some security issues appearing in o-ads embed github page and they seem linked to some old karma dependencies in obt. Any chance we can look at updating?

**Comment by notlee** [comment]
We don't have any immediate plans but are keeping an eye on issues as we work toward a replacement to obt. Is there a reason `o-ads-embed` includes `obt` as a dev dependency?

**Comment by SamiTriki** [comment]
It seems like it's using obt for the build process and demos 

https://github.com/Financial-Times/o-ads-embed/blob/master/.circleci/config.yml

**Comment by notlee** [comment]
It would be great for `o-ads-embed` to be more like other Origami components. I'd suggest removing it as a devDependency and updating circleci conf to be more like this: https://github.com/Financial-Times/o-ads-embed/blob/15e61dcab5e7a5ca44229627ef2e13dc3de5ae3a/.circleci/config.yml

**Comment by notlee** [comment]
Closing in favour of https://github.com/Financial-Times/origami-build-tools/issues/675
