### ISSUE TITLE
syntax errors on origami.json

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/origami-build-tools#569]
If json syntax in `origami.json` is incorrect, `obt` says 'origami.json not found' instead of reporting the syntax error

**Comment by notlee** [comment]
Hmm looks ok for `obt verify` and `obt demo`.  Is there a different command you have in mind, or is it a fixed issue?

<img width="753" alt="screenshot 2018-12-04 at 17 51 47" src="https://user-images.githubusercontent.com/10405691/49462164-49aa2f80-f7ed-11e8-81c0-ca6b5aa0ab17.png">

**Comment by notlee** [comment]
I'm going to close this as the errors seem to have been improved, but let me know if I've missed anything
