### ISSUE TITLE
obt verify and obt demo require different origami.json format

### ISSUE THREAD

**Issue by alexflorisca** [Financial-Times/origami-build-tools#595]
## What

Running `obt verify` thinks the origami.json demos section should contain `title` properties instead of `name`.

## Details

origami.json has the format:
```
{
    ...
    "demos": [
    {
	    "name": "Individual-Ad",
	    "template": "/demos/src/individual.mustache",
	    "description": "",
	    ...
    }
    ...
    ]
}
```

When running `obt verify`, an error comes up saying that the `name` property of a demo should actually be `title`:

```
Failed linting:
    All demos require a title property which is non-empty and of type "string".
    
   The origami.json file does not conform to the specification at http://origami.ft.com/docs/syntax/origamijson/
```

The spec says it should be called `name`. And so does `obt demo`, which fails to run if I change `name` to `title` for all the demos specified in origami.json.

This relates to v8 of OBT.

**Comment by notlee** [comment]
Hey, [both name and title are required](https://origami.ft.com/spec/v1/manifest/#demos). The name is used for the filename of the generated demo html `individual-ad.html` and title is used for a human friendly heading in the registry e.g. `An Individual Advertisement`. Closing this issue!
