### ISSUE TITLE
Remove dependency on babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by aendrew** [Financial-Times/origami-build-tools#609]
# Feature request

## What

Relying on `babel-plugin-add-module-exports` in the toolchain allows Origami modules to rely on a deprecated export strategy that is wholly incompatible with Babel 7. Until all Origami modules export according the ES6 module spec, downstream tooling cannot upgrade to Babel 7+ either.

## Details

In Babel 5, the default export would correspond to `module.exports`; in Babel 6, this changes to `module.exports.default`. The Babel plugin, `babel-plugin-add-module-exports`, reverts the output to the Babel 5 behaviour, at the cost of being incompatible with future versions of Babel.

Effectively the only benefit derived by using `babel-plugin-add-module-exports` is to allow pure-CommonJS users to not have to specify `default` when using `require()` to import modules. 

This is not a small piece of work — it ultimately requires modules in the Origami registry to stop using CommonJS syntax, or to adapt imports from `const something = require("o-something");` to `const {default: something} = require("o-something");` — but given that ES6 modules are a standard that is not going away and is increasingly web-native, and given that the reliance on the old import style prevents downstream toolchain upgrades, and also given that most Origami modules are consumed via some sort of toolchain that involves Babel anyway, it's probably worth doing at some point.

**Comment by notlee** [comment]
We're already on this! As part of the major cascade we're striping out any CommonJS syntax

**Comment by aendrew** [comment]
Omg that's very awesome news 🎉 🎊

**Comment by notlee** [comment]
All the components we maintain now use esm syntax exclusively! :D We just need to remove this plugin from obt and release a major. Closing in favour of this issue https://github.com/Financial-Times/origami-build-tools/issues/675
