### ISSUE TITLE
Add compilation speed tests?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#620]
We should be able to detect when component compilation times increase.

Compilation time increases can especially be a problem when a component is included multiple times (a speed test should consider silent and non-silent compilation times):
See https://github.com/Financial-Times/o-colors/pull/240

**Comment by chee** [comment]
yes! how about as part of [origami-bundle-size-cli](/Financial-Times/origami-bundle-size-cli), so the fox can warn on PR about that too?
