### ISSUE TITLE
Feature-request: do not include `default` polyfills

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#622]
This can give the false impression a component works in a browser without polyfills.
Only polyfills requested in `origami.json` (`browserFeatures.required`) should be included.
https://github.com/Financial-Times/origami-build-tools/blob/cf219aa5029754feb0f98c63db87f2af4a439786/lib/helpers/construct-polyfill-url.js#L32

**Comment by JakeChampion** [comment]
good suggestion! We should definitely do this :-)

**Comment by notlee** [comment]
We just did this
