### ISSUE TITLE
Upgrade or remove depenendecies and add dependabot

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#675]
Review obt dependencies and either upgrade or remove them, 
and add dependabot when we're up to date.

The following should be prioritised as they are one or more major behind.

- [x] aliases
- [x] app-root-path
- [x] autoprefixer
- [x] babel-loader
- [x] babel-plugin-add-module-exports ([safe to remove now, requires a major](https://github.com/Financial-Times/origami-build-tools/issues/609))
- [x] babel-preset-env
- [x] chalk
- [x] chokidar
- [x] deglob
- [x] elegant-spinner
- [x] eslint
- [x] figures
- [x] flush-write-stream
- [x] fs-extra
- [x] globby
- [x] indent-string
- [x] is-ci
- [x] karma
- [x] karma-chrome-launcher
- [x] karma-scss-preprocessor
- [x] karma-webpack
- [x] log-symbols
- [x] log-update
- [x] meow
- [x] merge-stream
- [x] mocha
- [x] mustache
- [x] parse-gitignore
- [x] raw-loader
- [x] sass-true
- [x] serve
- [x] sinon
- [x] through2
- [x] update-notifier
- [x] webpack
- [x] @financial-times/origami-service-makefile
- [x] eslint-plugin-json
- [x] eslint-plugin-mocha
- [x] eslint-plugin-node
- [x] eslint-plugin-promise
- [x] merge-deep
- [x] node-version
- [x] rimraf

see https://github.com/Financial-Times/origami-build-tools/pull/676

**Comment by JakeChampion** [comment]
I've started these --> https://github.com/Financial-Times/origami-build-tools/pull/676

**Comment by notlee** [comment]
released in v10 https://github.com/Financial-Times/origami-build-tools/pull/679/
