### ISSUE TITLE
Let's fork v5 to a build-service specific tool

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-build-tools#715]
Since v5, obt has [changed the sass compiler](https://github.com/Financial-Times/origami-build-tools/commit/5675b09cd76933b4ae3f90e6e542b783144a69f8) and [stopped shipping babel polyfills](https://github.com/Financial-Times/origami-build-tools/commit/96c677f6dfb20cdcff3d7ce99d6c1999d6c941c5) and probably a bunch of other stuff!
For backwards-compatibility the [origami-build-service](https://github.com/Financial-Times/origami-build-service) is [stuck on v5](https://github.com/Financial-Times/origami-build-service/blob/master/package.json#L43)!

Here's my quick proposal:

1. Let's fork v5 to a build-service specific tool. Name ideas? `origami-build-service-build-tool`? i'm going to call it `obt5fork` for the rest of this document
2. Let's upgrade all the dependencies of `obt5fork` and make sure we don't break anything!
3. Let's remove the command line interface of `obt5fork`, and any dependencies used for the command line interface
4. Let's remove from `obt5fork` any abilities that the build-service doesn't require, and any dependencies that support those
5. Let's remove as much code and dependencies as possible from `obt5fork` without the build-service output changing

**Comment by JakeChampion** [comment]
Yes please!

**Comment by notlee** [comment]
Yes! `origami-build-service-build-tool` works

**Comment by JakeChampion** [comment]
We could inline it into the build-service codebase?

**Comment by notlee** [comment]
>We could inline it into the build-service codebase?

👍

**Comment by chee** [comment]
i'm working on it here for now: https://github.com/Financial-Times/obt5fork names and inlining and so on can come once we have made a nice reduced version of it. about to do a PR to remove the demo server
