### ISSUE TITLE
proposal: update obt v10 interface

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#735]
We decided to make obt v10 a specific tool for authoring components in development.
Where we use obt for non-components we are [replacing obt with other tools](https://github.com/Financial-Times/origami/issues/47).

Jake has opened [a PR to remove the production flag](https://github.com/Financial-Times/origami-build-tools/pull/725). That's great, and I would
like to propose that we take the opportunity to introduce other interface changes.

When working on a component I use the following command. Usually I end up
sharing this with other engineers when they start working on a component for
for the first time (there are a lot of options to get your head around):
`obt demo --run-server --watch --verbose --brand=master`

I tend also to use:
`obt test`
`obt verify`

And if there's a tricky JS test failure that needs some debugging:
`obt test --debug`

We should review the interface more thoroughly, I have a few more ideas,
with more input from engineers outside the team. But I'm keen not to 
endlessly increase the scope of v10. For now I propose quick wins that mostly 
strip away options we do not need:

- Remove any flag which isn't compatible with the Origami spec (i.e. our sass/js entry points) or any flag that isn't necessary when working on a component (build destination flags). 
- Default to and remove`--verbose` from all commands. Do not replace with `--quite`. In development or ci builds we always want to see warning and debug logs. 
- Remove ` --run-server --watch` from the `demo` command. Keep the demo command for building demos in ci as usual.
- Add a `dev` command with one `brand` flag which behaves the same as `obt demo --run-server --watch --verbose --brand=master`
- Default to and remove the `--suppress-error` flag, which we use with `--demo-filter` [in ci](https://github.com/Financial-Times/origami-ci-tools/blob/f16d33b3c266356484f52c70d7f50c522ff8d5b2/commands/branch.js#L29) to prevent errors when the filtered demo isn't found.

```diff
	Usage
		$ obt <command> [<options>]

	Commands
+		develop, dev  Build demos locally every time a file changes and run a server to view them.
		build, b      Build CSS and JS in current directory
		demo, d       Build demos into the demos directory
		init          Initialise a new component with a boilerplate folder structure
		install, i    Install npm and bower dependencies required to build modules
		test, t       Run Origami specification tests and component specific tests
		verify, v     Check folder and code structure follows Origami specification

	Options
		-h, --help                 Print out this message
-		--watch                    Re-run every time a file changes
-		--run-server               Build demos locally and runs a server
-		--js=<path>                Main JavaScript file (default: ./src/main.js)
-		--sass=<path>              Main Sass file (default: ./src/main.scss)
-		--build-js=<file>          Compiled JavaScript file (default: main.js)
-		--build-css=<file>         Compiled CSS file (default: main.css)
-		--build-folder=<dir>       Compiled assets directory (default: ./build/)
		-v, --version              Print out version of origami-build-tools
-		--production               Compiled assets will be minified for production systems
		--browserstack             Run tests using Browserstack instead of Chrome Stable
-		--standalone               Create a named export for the built JavaScript
		--demo-filter=<demo-name>  Build a specific demo. E.G. --demo-filter=pa11y to build only the pa11y.html demo.
		--brand=<brand-name>       Build SCSS for a given brand. E.G. --brand=internal to build the component for the internal brand.
-		--suppress-error          sDo not error if no demos are found when using the --demo-filter option.
		--debug                    Keep the test runner open to enable debugging in any browser.
-		--verbose                  Output sass warnings with backtraces.
```

**Comment by JakeChampion** [comment]
Yes please, I agree with all this

**Comment by chee** [comment]
Yes please, I agree with all this

**Comment by notlee** [comment]
released in v10 https://github.com/Financial-Times/origami-build-tools/pull/679/
