### ISSUE TITLE
Pass the `ignoreBower` bower flag through from demo to `buildSass`

### ISSUE THREAD

**Issue by chee** [Financial-Times/origami-build-tools#737]
It looks like `ignoreBower` doesn't get passed through to `buildSass`:

https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/demo-build.js#L40-L52

it would be good if it was, because that's how `node_modules` gets added to the sass include paths here: https://github.com/Financial-Times/origami-build-tools/blob/6caa57266583f7fd7d563f37cea2f869e28db00f/lib/helpers/files.js#L205-L208

**Comment by alexflorisca** [comment]
This was solved in https://github.com/Financial-Times/origami-build-tools/pull/739 and https://github.com/Financial-Times/origami-build-tools/pull/738
