### ISSUE TITLE
proposal: facilitiate mocking imports

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#746]
origami-build-tools compiles components before running tests in karma. Reportedly this has meant mocking imports e.g. with `proxyquire` is difficult or impossible. oat should ensure there's a solution to mocking imports.

**Comment by JakeChampion** [comment]
What types of imports are we mocking? I'm wondering whether we need to do any mocking of imports at all

**Comment by notlee** [comment]
Agreed. I do not remember the context
