### ISSUE TITLE
obt demo

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#749]
## `obt demo`

This command is the one which is going to be used the most day-to-day for Origami component authors. 

A components' demos are currently written using [Mustache](https://mustache.github.io) templates and gathering data from the components' [`origami.json` file](https://origami-test.ft.com/spec/v1/manifest/#demos).

We are planning on making demos for components with [ReactJS](https://reactjs.org/) instead of [Mustache](https://mustache.github.io) templates.

The workflow of most Origami component authors with the current tooling is: `obt demo --run-server --watch --verbose  --port 3000 --brand=internal`. We should think about having some of those flags be the default instead of making the authors have to type them out all the time.

Feedback from some Origami component authors is that the build time for demos is rather slow and that it is sometimes difficult to see when a build has failed and why it has failed. We should look into having a fast build with some type of server that can handle errors and display them in a nice format on the terminal as well as on the webpage of the demo.

Some more feedback from authors is that the command should display all warnings/deprecations/concerns to the console so that the author can know during their development workflow about the warnings/deprecations/concerns.

**Comment by chee** [comment]
let's create a greenfield standalone component demo command, and then use that in obt

**Comment by notlee** [comment]
Closing because more imminent `obt demo` changes are captured here:
https://github.com/Financial-Times/origami-build-tools/issues/735
