### ISSUE TITLE
Improve the karma-scrumple error message when dependencies have not been installed

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#850]
## What
I ran `obt test` in a component repository before running `obt install` and was given a useful error message but it was surrounded by lots of extra information which I don't think is necessary for a component developer to have to read.

This is the error I see:
```
 ❯ Running Karma tests on Chrome Stable
   ⠸ Starting Karma server
14 07 2020 14:29:19.039:ERROR [preprocessor.scrumple]: Failed to process ./test/events/page.test.js

Error: Command failed with exit code 101: /Users/jake.champion/.nvm/versions/node/v14.4.0/lib/node_modules/origami-build-tools/node_modules/scrumple/node_modules/@financial-times/scrumple-darwin/scrumple --map-inline --input /Users/jake.champion/Code/repo-data-cli/repos/o-tracking/test/events/page.test.js --for-bower --allow-npm-dev-deps
thread 'main' panicked at 'no package.json at "/Users/jake.champion/Code/repo-data-cli/repos/o-tracking/node_modules/origami-build-tools/package.json". have you run `npm install`?: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:131:19
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The bit which is helpful to me is the 'no package.json at "/Users/jake.champion/Code/repo-data-cli/repos/o-tracking/node_modules/origami-build-tools/package.json". have you run `npm install`?".

The other parts I found not helpful and a bit confusing to read.

Hopefully it is possible to remove the Rust specific parts like:
```
: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:131:19 
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Details
How to reproduce:
- Open a terminal to an Origami component which has dependencies and tests such as o-tracking
- Run `obt test` and it should fail with `preprocessor.scrumple` error.

**Comment by chee** [comment]
we don't use scrumple anymore
