### ISSUE TITLE
Require component lint configuration

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#876]
If a component has an `.eslintrc.js` or `.stylelintrc.js` file that configuration is used for linting rules by the `obt verify` command. If not provided default configuration is used. This does/should [apply to `.remarkrc.js` too](https://github.com/Financial-Times/origami-build-tools/issues/875).

The team decided instead of falling back to default configuration origami-build-tools should throw an error. We think this is more transparent and ensures components provide local configuration, which can be used by other tools such as text editors to present errors to enginers before running origami build tools.

**Comment by notlee** [comment]
Opps, Jake had started this but I picked it up again! 🙈 See: https://github.com/Financial-Times/origami-build-tools/pull/926

**Comment by JakeChampion** [comment]
I believe we are now not going to add this feature and instead will add to the origami v2 spec that components should/must have their own `lint` npm run-script. -- https://github.com/Financial-Times/origami-build-tools/pull/926#issuecomment-731081612

**Comment by notlee** [comment]
Let's keep this open until we create new issue(s). We should also capture in an issue that I've opened a PR to move the tests which confirm our stylelint config to stylelint-config-origami-component, they can be removed from obt:
https://github.com/Financial-Times/stylelint-config-origami-component/pull/31

**Comment by notlee** [comment]
This work has been completed and will be released in the next major version (v11):
https://github.com/Financial-Times/origami-build-tools/pull/935
