### ISSUE TITLE
Is it ok that component configuration is dynamically required?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#881]
It's possible to execute arbitary code from components as part of the `obt verify` task as the configuration files for linting (`.eslintrc.js` and `.stylelintrc.js`) are required. I think as we trust the input (origami components) this is probably ok. But we could instead which our config to `json` files.

**Comment by JakeChampion** [comment]
I think it is ok, yes. 

origami-build-tools is a developer dependency and so is only meant to run on a development machine, not a production machine.

the `obt verify` task only reads the top-level config file, not any dependencies config files, so the code being executed is code within the codebase they are working on.
