### ISSUE TITLE
major: throw an error when `obt verify` finds readme issues?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#883]
currently the behaviour is to warn in CI instead of throw an error

**Comment by JakeChampion** [comment]
@Financial-Times/origami-core, as we are working on a new major version of the build-tools now, we should have this discussion and decide if we want to make this change.

My understanding is there are three options to choose from:
1.  Turn all warnings into errors
2.  Turn some warning into errors and keep others as warnings
3.  Turn no warnings into errors, keeping them all as warning

If we went with option 2, we would need to agree on what to turn into an error and what to keep as a warning.
