### ISSUE TITLE
feature: install demo dev dependencies instead of using the build service

### ISSUE THREAD

**Issue by notlee** [Financial-Times/origami-build-tools#906]
The feature request is lazy issue making, there might be other options, the problems to solve are:

- Currently demo dependencies listed in `origami.json` are included with a build service url along with a separate local build of the component. This means locally a demo may include a dependency which conflicts with a component dependency. When released the demo will then break unexpectedly and often goes unnoticed.

- The polyfills required by demo dependencies, as defined in the `origami.json` `browserFeatures` property, are not included in the demo html.

**Comment by JakeChampion** [comment]
@Financial-Times/origami-core, would this be solved by the [proposal for convention over configuration for demos](https://github.com/Financial-Times/origami/issues/82)?
