### ISSUE TITLE
Feature: check the built demo html is syntactically valid

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-build-tools#982]
## What
Currently obt does not check whether a component's demo html is syntactically valid. This means that a component's demo html could contain syntax errors, which is not ideal.

## Details
I was writing tests for the origami build service demos endpoints and came to write a test to see how those endpoints handle broken html in demos, whilst doing that work we realised that obt doesn't have a test for this and doesn't offer funtcionality to detect broken html. obt likely should offer this functionaliy, likely under the `obt verify` command, but that is to be decided.

## Additional information
To verify if the html in demos is valid, we first need to build the demos. If `obt verify` was the command to do this html verification then it would need to be modified to build the demos first.

**Comment by notlee** [comment]
For example check the placeholder demo of o-video@6.1.3 fails the check:
https://github.com/Financial-Times/origami-build-service/pull/494
